### ISSUE TITLE
Please release version 0.1 (to pypi)

### ISSUE THREAD

**Issue by aviad** [packagelib/flask-avro#3]
@bitbier - this seems like a great extension. Could you please release 0.1? pypi currently has only 0.0.0 as far as I can tell. (I can, of course clone this, but for work it'll be easier if a formal version is released..)

Thank you!

**Comment by bitbier** [comment]
Hey @aviad,

Sorry for the late reply. I'll definitely get this up there this weekend. Sorry been a busy week for me.

Cheers,

Jeff

**Comment by aviad** [comment]
Thanks!

**Comment by bitbier** [comment]
[Version 0.1](https://pypi.python.org/pypi/flask-avro) should be up on pypi now. Again, this project is pretty defunct or not getting a lot of love as we moved on to using pyramid. Although please me know if there is anything that I can do, or if you would like to take on the project. When I have some more time, I do wanna come back to this and clean it up a bit, but I hope that this is a good starting point for people.

Cheers!
